fn main() {
    // tauri-build does not add icons/** to Cargo's input set, so without these
    // the binary keeps embedding the previous .icns after the icon is
    // regenerated: the new file is on disk, the old one is still in the Dock.
    println!("cargo:rerun-if-changed=icons");
    println!("cargo:rerun-if-changed=icons/icon.icns");
    println!("cargo:rerun-if-changed=icons/icon.png");
    println!("cargo:rerun-if-changed=icons/icon.ico");
    println!("cargo:rerun-if-changed=icons/icon.svg");
    println!("cargo:rerun-if-changed=icons/tray-iconTemplate.png");
    println!("cargo:rerun-if-changed=icons/tray-iconTemplate@2x.png");
    println!("cargo:rerun-if-changed=icons/tray-icon-source.svg");
    // The macOS 26 layered icon: the compiled catalogue that ships in the
    // bundle, and the source it is built from. Assets.car is generated by
    // scripts/build-macos-glass-icon.sh and committed, so a stale one here is
    // the same failure mode as a stale .icns — new file on disk, old icon in
    // the Dock.
    println!("cargo:rerun-if-changed=icons/Assets.car");
    println!("cargo:rerun-if-changed=icons/Paper.icon");
    println!("cargo:rerun-if-changed=Info.plist");
    println!("cargo:rerun-if-changed=tauri.conf.json");

    /* The Swift runtime's rpath, published by `tauri-plugin-voices` under its
     * `links` key. Needed HERE because `cargo:rustc-link-arg` reaches only the
     * crate that emits it: the voices crate links its Swift archive, and this
     * binary links the voices crate, and without the rpath this binary dies at
     * launch with "Library not loaded ... no LC_RPATH's found" — before a
     * single test runs. Absent when the desktop feature is off, so a phone
     * build adds nothing. */
    if let Ok(runtime) = std::env::var("DEP_TAURI_PLUGIN_VOICES_SWIFT_RUNTIME") {
        println!("cargo:rustc-link-arg=-Wl,-rpath,{runtime}");
    }

    tauri_build::build()
}
