fn main() {
    // tauri-build does not add icons/** to Cargo's input set, so without these
    // the binary keeps embedding the previous .icns after the icon is
    // regenerated: the new file is on disk, the old one is still in the Dock.
    println!("cargo:rerun-if-changed=icons");
    println!("cargo:rerun-if-changed=icons/icon.icns");
    println!("cargo:rerun-if-changed=icons/icon.png");
    println!("cargo:rerun-if-changed=icons/icon.ico");
    println!("cargo:rerun-if-changed=icons/icon.svg");
    println!("cargo:rerun-if-changed=icons/tray-iconTemplate.png");
    println!("cargo:rerun-if-changed=icons/tray-iconTemplate@2x.png");
    println!("cargo:rerun-if-changed=icons/tray-icon-source.svg");
    // The macOS 26 layered icon: the compiled catalogue that ships in the
    // bundle, and the source it is built from. Assets.car is generated by
    // scripts/build-macos-glass-icon.sh and committed, so a stale one here is
    // the same failure mode as a stale .icns — new file on disk, old icon in
    // the Dock.
    println!("cargo:rerun-if-changed=icons/Assets.car");
    println!("cargo:rerun-if-changed=icons/Paper.icon");
    println!("cargo:rerun-if-changed=Info.plist");
    println!("cargo:rerun-if-changed=tauri.conf.json");

    tauri_build::build()
}
