//! Link the Qwen engine's Swift half, on macOS and nowhere else.
//!
//! Three things here are requirements the phase-30 spike paid for, not taste:
//!
//! - **The Metal Toolchain component must be installed** on every machine and
//!   CI runner that compiles this: `xcodebuild -downloadComponent MetalToolchain`
//!   (839 MB, no `sudo`). Without it the build dies at "CompileMetalFile …
//!   failed", which reads like a problem with the source.
//! - **The Apple frameworks must be named here.** `swift-rs` links the Swift
//!   runtime and nothing else, so without these the Rust binary fails to link
//!   with undefined BNNS and cblas symbols.
//! - **`mlx-swift_Cmlx.bundle` must ship inside the app bundle** — it is named
//!   in `tauri.conf.json`'s `bundle.resources` for that reason. Linking is not
//!   enough: MLX looks for its Metal shaders at run time and dies with "Failed
//!   to load the default metallib" when they are not there.
//!
//!   ⚠️ **AND THE PATH IT IS COPIED FROM IS A BUILD OUTPUT**, so the Swift half
//!   must have been built before `tauri build` runs — which it always has been,
//!   because this script builds it. A `tauri build` that somehow ran first
//!   would fail on a missing resource rather than produce an app that cannot
//!   speak, which is the right way round.
//!
//! Off macOS this does nothing, and `qwen::engine` refuses by name instead.

/// Every command the plugin exposes, by its Rust name. `tauri_plugin::Builder`
/// writes one `allow-*` / `deny-*` pair per entry into
/// `permissions/autogenerated/commands/`, and `permissions/default.toml` is
/// where those grants are collected.
///
/// ⚠️ **OMISSION FROM THIS LIST DOES NOT MAKE A COMMAND UNREACHABLE** — it only
/// stops that command's permission pair being GENERATED, and a hand-written
/// `allow-` file grants it exactly as any other. `commands.rs`'s `lists_agree`
/// is what actually holds the three lists together. The peer plugin's `build.rs`
/// records the same finding, having paid for it.
const COMMANDS: &[&str] = &[
    "voices_catalogue",
    "voices_install",
    "voices_stop",
    "voices_remove",
    "voices_render",
    "voices_render_file",
    "voices_release",
];

/// Where macOS keeps the Swift runtime dylibs a Swift archive asks for by
/// `@rpath`. A system path, so it is correct inside a shipped bundle.
const SWIFT_RUNTIME: &str = "/usr/lib/swift";

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();

    // Rebuilt when the bridge changes; the package manifest is watched too, so
    // a dependency bump is not silently ignored.
    println!("cargo:rerun-if-changed=swift/QwenKit/Sources/QwenKit/QwenKit.swift");
    println!("cargo:rerun-if-changed=swift/QwenKit/Package.swift");

    // Declared so `cfg(qwen_bridge)` is a known name rather than an unexpected
    // one, which since Rust 1.80 is a warning at every use.
    println!("cargo:rustc-check-cfg=cfg(qwen_bridge)");
    println!("cargo:rerun-if-env-changed=PAPER_VOICES_NO_SWIFT");

    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("macos") {
        return;
    }

    // An escape hatch for a machine that cannot build the Swift half — no Metal
    // toolchain, or a checkout with no network.
    //
    // ⚠️ **IT SETS A `cfg` RATHER THAN JUST SKIPPING THE LINK.** Skipping alone
    // leaves the `extern "C"` declarations with nothing to resolve to, so the
    // CRATE fails to link and the hatch cannot be used for the thing it exists
    // for. With the cfg off, `qwen::engine` compiles its refusing shape — the
    // same one every non-macOS build gets — so the app builds and says it has
    // no Chinese voice instead of silently having one that cannot speak.
    if std::env::var("PAPER_VOICES_NO_SWIFT").is_ok() {
        println!("cargo:warning=PAPER_VOICES_NO_SWIFT is set: the Qwen engine is not built in");
        return;
    }

    link_qwenkit();
    println!("cargo:rustc-cfg=qwen_bridge");
}

/// Build the Swift package and tell the linker where its archive is.
///
/// ⚠️ **THIS WAS `swift_rs::SwiftLinker` AND COULD NOT BE**, which is worth
/// recording because the failure is one version bump away from anybody:
/// `swift-rs` looks for the archive at SwiftPM's LEGACY path,
/// `<scratch>/<triple>/release`, and Swift 6.4's build system writes
/// `<scratch>/out/Products/Release` with a `release` symlink beside it. The
/// link then fails with *"could not find native static library QwenKit"* after
/// a twenty-minute build. It also builds into a scratch path of its own, so the
/// package's own `.build` — already warm — is compiled a second time.
///
/// Doing it here is about thirty lines because the C ABI needs nothing from
/// `swift-rs` at all: no Swift types cross the boundary, only pointers and
/// integers.
fn link_qwenkit() {
    let manifest =
        std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let package = manifest.join("swift/QwenKit");
    // Matched to the Rust profile, so a release build links a release archive.
    let profile = if std::env::var("PROFILE").as_deref() == Ok("release") {
        "release"
    } else {
        "debug"
    };

    let built = std::process::Command::new("swift")
        .args(["build", "-c", profile, "--package-path"])
        .arg(&package)
        .status()
        .expect("swift build could not be started — is Xcode's toolchain installed?");
    assert!(
        built.success(),
        "swift build failed for {}",
        package.display()
    );

    // ⚠️ THE ARCHIVE IS LOOKED FOR, NEVER ASSUMED. `swift build` can exit 0
    // having written nothing where this expects it — which is exactly how the
    // `swift-rs` failure above presented, and the same shape as `actool` and
    // `screencapture` elsewhere in this tree. Both layouts are tried because
    // which one a machine writes depends on its Swift version.
    let candidates = [
        package.join(format!(".build/{profile}")),
        package.join(format!(
            ".build/out/Products/{}",
            if profile == "release" {
                "Release"
            } else {
                "Debug"
            }
        )),
        package.join(format!(".build/arm64-apple-macosx/{profile}")),
    ];
    let found = candidates
        .iter()
        .find(|dir| dir.join("libQwenKit.a").is_file())
        .unwrap_or_else(|| {
            panic!(
                "swift build exited 0 but wrote no libQwenKit.a; looked in {}",
                candidates
                    .iter()
                    .map(|d| d.display().to_string())
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        });

    println!("cargo:rustc-link-search=native={}", found.display());
    println!("cargo:rustc-link-lib=static=QwenKit");

    // The Swift runtime the archive's autolink records name. Without these the
    // link fails on `_swift_retain` and its siblings.
    println!("cargo:rustc-link-search=native=/usr/lib/swift");
    // ⚠️ AND A SEARCH PATH IS NOT AN RPATH. Two of the runtime's dylibs are
    // referenced as `@rpath/...` — `libswift_Concurrency` and
    // `libswiftCompatibilitySpan` — so a binary that LINKED perfectly then died
    // at launch with "Library not loaded ... no LC_RPATH's found". `/usr/lib/swift`
    // is where macOS keeps them, so this is a system path rather than a path
    // into somebody's Xcode, and it is correct in a shipped bundle too.
    println!("cargo:rustc-link-arg=-Wl,-rpath,{SWIFT_RUNTIME}");
    // ⚠️ AND A LINK ARG REACHES THIS CRATE ONLY. Anything that LINKS this one
    // — the app, and its test binary — needs the same rpath and does not
    // inherit it: `cargo:rustc-link-arg` is not propagated to dependents, only
    // `link-lib` and `link-search` are. Measured: `cargo test --workspace`
    // died before a single test ran. So the path is published as metadata
    // under this crate's `links` key, and the app's own `build.rs` reads
    // `DEP_TAURI_PLUGIN_VOICES_SWIFT_RUNTIME` — which is absent when the
    // desktop feature is off, so a build without this plugin adds nothing.
    println!("cargo:swift-runtime={SWIFT_RUNTIME}");
    if let Some(toolchain) = swift_runtime_dir() {
        println!("cargo:rustc-link-search=native={toolchain}");
    }

    // MLX and the audio stack; the archive names the frameworks it needs, but
    // the linker still has to be told they are frameworks.
    for framework in [
        "Accelerate",
        "Metal",
        "MetalKit",
        "MetalPerformanceShaders",
        "MetalPerformanceShadersGraph",
        "Foundation",
        "AVFoundation",
        "CoreAudio",
        "CoreML",
        "QuartzCore",
        "NaturalLanguage",
    ] {
        println!("cargo:rustc-link-lib=framework={framework}");
    }
}

/// Where the toolchain keeps its Swift runtime dylibs.
fn swift_runtime_dir() -> Option<String> {
    let out = std::process::Command::new("xcrun")
        .args(["--find", "swift"])
        .output()
        .ok()?;
    let swift = std::path::PathBuf::from(String::from_utf8(out.stdout).ok()?.trim());
    // .../usr/bin/swift -> .../usr/lib/swift/macosx
    let lib = swift.parent()?.parent()?.join("lib/swift/macosx");
    lib.is_dir().then(|| lib.display().to_string())
}
