//! Link the Qwen engine's Swift half, on macOS and nowhere else.
//!
//! Three things here are requirements the phase-30 spike paid for, not taste:
//!
//! - **The Metal Toolchain component must be installed** on every machine and
//!   CI runner that compiles this: `xcodebuild -downloadComponent MetalToolchain`
//!   (839 MB, no `sudo`). Without it the build dies at "CompileMetalFile …
//!   failed", which reads like a problem with the source.
//! - **The Apple frameworks must be named here.** `swift-rs` links the Swift
//!   runtime and nothing else, so without these the Rust binary fails to link
//!   with undefined BNNS and cblas symbols.
//! - **`mlx-swift_Cmlx.bundle` must ship inside the app bundle** — it is named
//!   in `tauri.conf.json`'s `bundle.resources` for that reason. Linking is not
//!   enough: MLX looks for its Metal shaders at run time and dies with "Failed
//!   to load the default metallib" when they are not there.
//!
//!   ⚠️ **AND THE PATH IT IS COPIED FROM IS A BUILD OUTPUT**, so the Swift half
//!   must have been built before `tauri build` runs — which it always has been,
//!   because this script builds it. A `tauri build` that somehow ran first
//!   would fail on a missing resource rather than produce an app that cannot
//!   speak, which is the right way round.
//!
//! Off macOS this does nothing, and `qwen::engine` refuses by name instead.

/// Every command the plugin exposes, by its Rust name. `tauri_plugin::Builder`
/// writes one `allow-*` / `deny-*` pair per entry into
/// `permissions/autogenerated/commands/`, and `permissions/default.toml` is
/// where those grants are collected.
///
/// ⚠️ **OMISSION FROM THIS LIST DOES NOT MAKE A COMMAND UNREACHABLE** — it only
/// stops that command's permission pair being GENERATED, and a hand-written
/// `allow-` file grants it exactly as any other. `commands.rs`'s `lists_agree`
/// is what actually holds the three lists together. The peer plugin's `build.rs`
/// records the same finding, having paid for it.
const COMMANDS: &[&str] = &[
    "voices_catalogue",
    "voices_install",
    "voices_stop",
    "voices_remove",
    "voices_render",
    "voices_render_file",
    "voices_release",
];

/// Where macOS keeps the Swift runtime dylibs a Swift archive asks for by
/// `@rpath`. A system path, so it is correct inside a shipped bundle.
const SWIFT_RUNTIME: &str = "/usr/lib/swift";

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();

    // Rebuilt when the bridge changes; the package manifest is watched too, so
    // a dependency bump is not silently ignored.
    println!("cargo:rerun-if-changed=swift/QwenKit/Sources/QwenKit/QwenKit.swift");
    println!("cargo:rerun-if-changed=swift/QwenKit/Package.swift");

    // Declared so `cfg(qwen_bridge)` is a known name rather than an unexpected
    // one, which since Rust 1.80 is a warning at every use.
    println!("cargo:rustc-check-cfg=cfg(qwen_bridge)");
    println!("cargo:rerun-if-env-changed=PAPER_VOICES_NO_SWIFT");

    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("macos") {
        return;
    }

    // An escape hatch for a machine that cannot build the Swift half — no Metal
    // toolchain, or a checkout with no network.
    //
    // ⚠️ **IT SETS A `cfg` RATHER THAN JUST SKIPPING THE LINK.** Skipping alone
    // leaves the `extern "C"` declarations with nothing to resolve to, so the
    // CRATE fails to link and the hatch cannot be used for the thing it exists
    // for. With the cfg off, `qwen::engine` compiles its refusing shape — the
    // same one every non-macOS build gets — so the app builds and says it has
    // no Chinese voice instead of silently having one that cannot speak.
    if std::env::var("PAPER_VOICES_NO_SWIFT").is_ok() {
        println!("cargo:warning=PAPER_VOICES_NO_SWIFT is set: the Qwen engine is not built in");
        return;
    }

    link_qwenkit();
    println!("cargo:rustc-cfg=qwen_bridge");
}

/// Build the Swift package and tell the linker where its archive is.
///
/// ⚠️ **THIS WAS `swift_rs::SwiftLinker` AND COULD NOT BE**, which is worth
/// recording because the failure is one version bump away from anybody:
/// `swift-rs` looks for the archive at SwiftPM's LEGACY path,
/// `<scratch>/<triple>/release`, and Swift 6.4's build system writes
/// `<scratch>/out/Products/Release` with a `release` symlink beside it. The
/// link then fails with *"could not find native static library QwenKit"* after
/// a twenty-minute build. It also builds into a scratch path of its own, so the
/// package's own `.build` — already warm — is compiled a second time.
///
/// Doing it here is about thirty lines because the C ABI needs nothing from
/// `swift-rs` at all: no Swift types cross the boundary, only pointers and
/// integers.
fn link_qwenkit() {
    let manifest =
        std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let package = manifest.join("swift/QwenKit");
    // Matched to the Rust profile, so a release build links a release archive.
    let profile = if std::env::var("PROFILE").as_deref() == Ok("release") {
        "release"
    } else {
        "debug"
    };

    let built = std::process::Command::new("swift")
        .args(["build", "-c", profile, "--package-path"])
        .arg(&package)
        .status()
        .expect("swift build could not be started — is Xcode's toolchain installed?");
    assert!(
        built.success(),
        "swift build failed for {}",
        package.display()
    );

    // ⚠️ THE ARCHIVE IS LOOKED FOR, NEVER ASSUMED. `swift build` can exit 0
    // having written nothing where this expects it — which is exactly how the
    // `swift-rs` failure above presented, and the same shape as `actool` and
    // `screencapture` elsewhere in this tree. Both layouts are tried because
    // which one a machine writes depends on its Swift version.
    let candidates = [
        package.join(format!(".build/{profile}")),
        package.join(format!(
            ".build/out/Products/{}",
            if profile == "release" {
                "Release"
            } else {
                "Debug"
            }
        )),
        package.join(format!(".build/arm64-apple-macosx/{profile}")),
    ];
    let found = candidates
        .iter()
        .find(|dir| dir.join("libQwenKit.a").is_file())
        .unwrap_or_else(|| {
            panic!(
                "swift build exited 0 but wrote no libQwenKit.a; looked in {}",
                candidates
                    .iter()
                    .map(|d| d.display().to_string())
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        });

    println!("cargo:rustc-link-search=native={}", found.display());
    println!("cargo:rustc-link-lib=static=QwenKit");

    ship_shaders(&package, &candidates);

    // The Swift runtime the archive's autolink records name. Without these the
    // link fails on `_swift_retain` and its siblings.
    println!("cargo:rustc-link-search=native=/usr/lib/swift");
    // ⚠️ AND A SEARCH PATH IS NOT AN RPATH. Two of the runtime's dylibs are
    // referenced as `@rpath/...` — `libswift_Concurrency` and
    // `libswiftCompatibilitySpan` — so a binary that LINKED perfectly then died
    // at launch with "Library not loaded ... no LC_RPATH's found". `/usr/lib/swift`
    // is where macOS keeps them, so this is a system path rather than a path
    // into somebody's Xcode, and it is correct in a shipped bundle too.
    println!("cargo:rustc-link-arg=-Wl,-rpath,{SWIFT_RUNTIME}");
    // ⚠️ AND A LINK ARG REACHES THIS CRATE ONLY. Anything that LINKS this one
    // — the app, and its test binary — needs the same rpath and does not
    // inherit it: `cargo:rustc-link-arg` is not propagated to dependents, only
    // `link-lib` and `link-search` are. Measured: `cargo test --workspace`
    // died before a single test ran. So the path is published as metadata
    // under this crate's `links` key, and the app's own `build.rs` reads
    // `DEP_TAURI_PLUGIN_VOICES_SWIFT_RUNTIME` — which is absent when the
    // desktop feature is off, so a build without this plugin adds nothing.
    println!("cargo:swift-runtime={SWIFT_RUNTIME}");
    if let Some(toolchain) = swift_runtime_dir() {
        println!("cargo:rustc-link-search=native={toolchain}");
    }

    // MLX and the audio stack; the archive names the frameworks it needs, but
    // the linker still has to be told they are frameworks.
    for framework in [
        "Accelerate",
        "Metal",
        "MetalKit",
        "MetalPerformanceShaders",
        "MetalPerformanceShadersGraph",
        "Foundation",
        "AVFoundation",
        "CoreAudio",
        "CoreML",
        "QuartzCore",
        "NaturalLanguage",
    ] {
        println!("cargo:rustc-link-lib=framework={framework}");
    }
}

/// The Metal shaders, put where a static bundle configuration can name them.
///
/// ⚠️ **THE RESOURCE PATH SAID `release` WHILE THIS BUILDS WHATEVER PROFILE CARGO
/// IS BUILDING, AND THAT COST FOUR CI RUNS TO SEE.** `tauri.macos.conf.json` has
/// to name one fixed path — the config is static JSON and cannot branch on a
/// profile — and it named `.build/release/mlx-swift_Cmlx.bundle`. A developer Mac
/// has that directory because somebody once ran a release build, so it worked
/// here; a clean checkout building `debug` (which `cargo clippy` and `pnpm verify`
/// both do) has only `.build/debug`, so the APP crate's build script died with
/// `resource path ... doesn't exist` — 275 seconds in, four layers below the line
/// that reads `cargo clippy -D warnings failed`.
///
/// So the bundle is copied to one profile-independent place and the config names
/// that. Six files and 4 MB, and `build.rs` only re-runs when its inputs change.
///
/// ⚠️ **AND IT IS CHECKED AFTERWARDS, NOT ASSUMED** — the same rule the archive
/// search above follows, and for the same reason: a copy that silently wrote
/// nothing would move the failure back to `tauri build`, which is where it was.
fn ship_shaders(package: &std::path::Path, candidates: &[std::path::PathBuf]) {
    const BUNDLE: &str = "mlx-swift_Cmlx.bundle";
    let build = package.join(".build");
    let into = build.join("paper");
    // ⚠️ **THE BUNDLE IS LOOKED FOR SEPARATELY FROM THE ARCHIVE, BECAUSE THEY ARE
    // NOT ALWAYS IN THE SAME DIRECTORY.** The first version of this took the
    // directory `libQwenKit.a` was found in and asserted the bundle was beside
    // it. On a developer Mac it is: `.build/debug` is a SYMLINK to
    // `out/Products/Debug`, so both appear there. On the CI runner the archive
    // was in `.build/debug` and the bundle was not, and the assertion fired —
    // correctly, and having assumed exactly what the archive search directly
    // above refuses to assume. Two artifacts, two searches.
    let from = candidates
        .iter()
        .map(|dir| dir.join(BUNDLE))
        .find(|path| path.is_dir())
        // And if SwiftPM moves it again, look: bounded, skipping the destination
        // so a previous run's copy is never taken for the source.
        .or_else(|| find_directory(&build, BUNDLE, &into, 4))
        .unwrap_or_else(|| {
            // ⚠️ **AND THE LIKELIEST CAUSE IS NAMED, BECAUSE IT COST FOUR CI RUNS
            // TO FIND WITHOUT IT.** `swift build` reports "Build complete!" and
            // exits 0 with no bundle when there is no `metal` to compile the
            // shaders the bundle exists to carry — Xcode ships the compiler
            // separately, and `AGENTS.md` records that every machine and CI runner
            // building this needs it. A message that says only "not found" sends
            // the next reader looking at layouts, which is where I looked.
            panic!(
                "swift build exited 0 but wrote no {BUNDLE} anywhere under {}.\n\
                 Without the shaders MLX dies at run time with \"Failed to load \
                 the default metallib\".\n\
                 Check the Metal compiler, which Xcode does not ship: \
                 `xcodebuild -downloadComponent MetalToolchain`, then \
                 `\"$(xcrun -f metal)\" --version`.\n\
                 What IS there:\n{}",
                build.display(),
                inventory(&build)
            )
        });
    let to = into.join(BUNDLE);
    // Replaced rather than merged: a stale shader left from an older MLX would
    // ship inside the app and be loaded in preference to nothing at all.
    let _ = std::fs::remove_dir_all(&to);
    std::fs::create_dir_all(&into).expect("a directory for the shaders");
    copy_tree(&from, &to).expect("the shaders could not be copied");
    assert!(
        to.join("Contents/Resources/default.metallib").is_file(),
        "{} holds no default.metallib, which is the one file MLX asks for by name",
        to.display()
    );
    println!("cargo:rerun-if-changed={}", from.display());
}

/// What a build directory holds, for a message that has to explain an absence.
///
/// ⚠️ **WRITTEN BECAUSE TWO GUESSES WERE SPENT ON THIS.** When the bundle is not
/// where it is expected, the useful question is what IS there — and a panic that
/// says only "not found" sends the next reader to invent a hypothesis and spend a
/// CI run on it. Twice, here: a layout difference, then a missing Metal compiler
/// which turned out to be installed and running. Every product directory and
/// every `.bundle` the walk can see, and the reader decides.
fn inventory(build: &std::path::Path) -> String {
    let mut lines = Vec::new();
    for dir in [build.to_path_buf(), build.join("out/Products")] {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        let mut names: Vec<String> = entries
            .flatten()
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .collect();
        names.sort();
        lines.push(format!("  {} → {}", dir.display(), names.join(", ")));
    }
    let mut bundles = Vec::new();
    collect_bundles(build, 5, &mut bundles);
    lines.push(if bundles.is_empty() {
        "  no *.bundle anywhere within five levels".to_owned()
    } else {
        format!("  bundles: {}", bundles.join(", "))
    });
    lines.join("\n")
}

/// Every `*.bundle` within `depth`, as paths, skipping symbolic links.
fn collect_bundles(root: &std::path::Path, depth: usize, into: &mut Vec<String>) {
    if depth == 0 {
        return;
    }
    let Ok(entries) = std::fs::read_dir(root) else {
        return;
    };
    for entry in entries.flatten() {
        if !entry.file_type().is_ok_and(|kind| kind.is_dir()) {
            continue;
        }
        let path = entry.path();
        if path.extension().is_some_and(|ext| ext == "bundle") {
            into.push(path.display().to_string());
        } else {
            collect_bundles(&path, depth - 1, into);
        }
    }
}

/// Find a directory by name, no deeper than `depth`, ignoring one subtree.
///
/// Symbolic links are stepped over rather than followed: `file_type` reports a
/// link as a link, so this walks only real directories and cannot loop. The
/// candidate paths above are checked with `is_dir`, which DOES follow a link, so
/// between them both layouts are covered.
fn find_directory(
    root: &std::path::Path,
    name: &str,
    skip: &std::path::Path,
    depth: usize,
) -> Option<std::path::PathBuf> {
    if depth == 0 {
        return None;
    }
    let mut deeper = Vec::new();
    for entry in std::fs::read_dir(root).ok()?.flatten() {
        if !entry.file_type().is_ok_and(|kind| kind.is_dir()) {
            continue;
        }
        let path = entry.path();
        if path == skip {
            continue;
        }
        if entry.file_name() == name {
            return Some(path);
        }
        deeper.push(path);
    }
    deeper
        .iter()
        .find_map(|dir| find_directory(dir, name, skip, depth - 1))
}

/// Copy a directory tree, creating what it needs.
fn copy_tree(from: &std::path::Path, to: &std::path::Path) -> std::io::Result<()> {
    std::fs::create_dir_all(to)?;
    for entry in std::fs::read_dir(from)? {
        let entry = entry?;
        let target = to.join(entry.file_name());
        if entry.file_type()?.is_dir() {
            copy_tree(&entry.path(), &target)?;
        } else {
            std::fs::copy(entry.path(), &target)?;
        }
    }
    Ok(())
}

/// Where the toolchain keeps its Swift runtime dylibs.
fn swift_runtime_dir() -> Option<String> {
    let out = std::process::Command::new("xcrun")
        .args(["--find", "swift"])
        .output()
        .ok()?;
    let swift = std::path::PathBuf::from(String::from_utf8(out.stdout).ok()?.trim());
    // .../usr/bin/swift -> .../usr/lib/swift/macosx
    let lib = swift.parent()?.parent()?.join("lib/swift/macosx");
    lib.is_dir().then(|| lib.display().to_string())
}
