import { webkit } from '@playwright/test'
const [cookie] = process.argv.slice(2)
const browser = await webkit.launch()
const ctx = await browser.newContext({ ignoreHTTPSErrors: true })
await ctx.addCookies([{ name: 'paper_session', value: cookie, domain: 'localhost', path: '/', httpOnly: true, secure: true, sameSite: 'Strict' }])
const page = await ctx.newPage()
await page.goto('https://localhost:27183', { waitUntil: 'domcontentloaded' })
await page.evaluate(() => { window.__ws = new WebSocket('wss://localhost:27183/ws'); window.__ws.binaryType = 'arraybuffer' })
console.log('holding')
await new Promise((r) => setTimeout(r, 25000))
await browser.close()
