/// Every command the plugin exposes, by its Rust name. `tauri_plugin::Builder`
/// writes one `allow-*` / `deny-*` pair per entry into
/// `permissions/autogenerated/commands/`, and `permissions/default.toml` is
/// where those grants are collected.
///
/// ⚠️ **OMISSION FROM THIS LIST DOES NOT MAKE A COMMAND UNREACHABLE** — it only
/// stops that command's permission pair being GENERATED, and a hand-written
/// `allow-` file grants it exactly as any other. `commands.rs`'s `lists_agree`
/// is what actually holds the three lists together. The peer and voices plugins
/// both record the same finding, having paid for it.
const COMMANDS: &[&str] = &[
    "passages_put",
    "passages_note",
    "passages_flush",
    "passages_forget",
    "passages_rekey",
    "passages_pending",
    "passages_indexed",
    "passages_rebuild",
    "passages_retry",
    "passages_status",
    "passages_search",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
