/// Every command the plugin exposes, by its Rust name. `tauri_plugin::Builder`
/// writes one `allow-*` / `deny-*` permission pair per entry into
/// `permissions/autogenerated/commands/`, and `permissions/default.toml` is
/// where those grants are actually collected. A command missing from this list
/// is unreachable from the webview no matter what the ACL says.
const COMMANDS: &[&str] = &[
    // WI-5.8
    "peer_status",
    "peer_local_role",
    // The role a reader can change. THIS LIST IS WHAT GENERATES THE
    // PERMISSIONS — `peer_set_local_role` was registered in `lib.rs` and its
    // permission file committed by hand, so the build was green on a tree
    // that already had the artifact and would have deleted it on the next
    // clean regeneration, leaving `default.toml` pointing at nothing.
    "peer_set_local_role",
    "paper_data_root",
    "fs_fsync",
    // WI-B.1 — peers and grants
    "peer_list_peers",
    "peer_forget_peer",
    "peer_set_grants",
    "peer_has_grant",
    // WI-B.2 — pairing
    "peer_pair_begin",
    "peer_pair_cancel",
    "peer_pair_confirm",
    "peer_pair_from_uri",
    // WI-B.3 — sessions
    "peer_ready",
    "peer_connect",
    "peer_send",
    "peer_session_recv",
    "peer_close",
    // WI-B.4 — blobs
    "peer_blob_fetch",
    "peer_hash_file",
];

fn main() {
    // Besides the permissions, this emits `cfg(mobile)` / `cfg(desktop)` from
    // the compile target, which is what `local_role()` keys on.
    tauri_plugin::Builder::new(COMMANDS).build();
}
