/// Every command the plugin exposes, by its Rust name. `tauri_plugin::Builder`
/// writes one `allow-*` / `deny-*` permission pair per entry into
/// `permissions/autogenerated/commands/`, and `permissions/default.toml` is
/// where those grants are actually collected.
///
/// ⚠️ **OMISSION FROM THIS LIST DOES NOT MAKE A COMMAND UNREACHABLE, AND THIS
/// SAID IT DID.** What it stops is the GENERATION of that command's permission
/// pair; a command registered in `lib.rs` whose `allow-` file was written by
/// hand is reachable exactly as any other, which is how
/// `peer_set_local_role` came to be committed by hand in the first place (see
/// the note beside it). What actually holds the three lists together is
/// `commands.rs`'s `lists_agree` test, and that is the thing to keep working.
/// Found by audit.
///
/// ⚠️ **AND REGENERATION DOES NOT DELETE A HAND-WRITTEN FILE EITHER.** The
/// generator writes the pairs for the entries it is given and leaves the rest
/// of the directory alone — so the hand-written artifact would have SURVIVED a
/// clean build and gone on granting a command this list does not name, which
/// is worse than the deletion the old comment feared. Both halves of that
/// paragraph were wrong; the conclusion — put the command here — was right.
const COMMANDS: &[&str] = &[
    // WI-5.8
    "peer_status",
    "peer_local_role",
    // The role a reader can change. THIS LIST IS WHAT GENERATES THE
    // PERMISSIONS — `peer_set_local_role` was registered in `lib.rs` and its
    // permission file committed by hand, so the build was green on a tree
    // that already had the artifact and would have deleted it on the next
    // clean regeneration, leaving `default.toml` pointing at nothing.
    "peer_set_local_role",
    "paper_data_root",
    // WI-B.1 — peers and grants
    "peer_list_peers",
    "peer_forget_peer",
    "peer_set_grants",
    "peer_has_grant",
    // WI-B.2 — pairing
    "peer_pair_begin",
    "peer_pair_cancel",
    "peer_pair_confirm",
    "peer_pair_from_uri",
    // WI-B.3 — sessions
    "peer_ready",
    "peer_connect",
    "peer_send",
    "peer_session_recv",
    "peer_close",
    // WI-B.4 — blobs
    "peer_blob_fetch",
    "peer_hash_file",
    // WI-22.B1 — the person identity. `peer_person_phrase` returns the
    // RECOVERY PHRASE, and does so because the design requires the twelve
    // words be re-showable — see `commands.rs`.
    //
    // ⚠️ **IT IS NOT THE ONLY COMMAND THAT RETURNS A SECRET, AND THIS SAID IT
    // WAS.** `peer_pair_begin` answers with a `paper://pair?…` URI and a QR
    // encoding of it, and that URI CARRIES THE PAIRING SECRET — anybody who
    // reads it off a screen can claim the offer. The difference is lifetime,
    // not sensitivity: a pairing secret is single-shot and short-lived, the
    // phrase restores an identity for ever. A list that names one secret and
    // implies there are no others is a list somebody screenshots the other by.
    // Found by audit.
    "peer_person_status",
    "peer_person_ensure",
    "peer_person_phrase",
    "peer_person_restore",
    "peer_person_forget",
    "peer_person_delegate",
    // WI-22.B3 — the circle roster
    "peer_circle_people",
    "peer_circle_introduce",
    "peer_circle_mine",
    // The roster's size read from the file, minting nothing — what the
    // Circle panel counts on every refresh. `peer_circle_mine` renews and
    // refuses, which a status read must never do.
    "peer_circle_roster",
    "peer_page_sign",
    "peer_circle_remember",
    "peer_circle_revoke",
    "peer_circle_forget",
    // Phase 25 — public sharing. TWO of these touch only the disk:
    // `peer_share_offered` reads the policy file, and `peer_share_publish_note`
    // appends a line to one book's own annotation file. Every other one starts
    // the share endpoint — a UDP bind, a second key and a blob store.
    //
    // (This said "every other one", which was wrong about publishing a note —
    // so writing one read as a network act. Found by audit.)
    "peer_share_id",
    "peer_share_offered",
    "peer_share_offer_bytes",
    "peer_share_offer_notes",
    "peer_share_withdraw",
    "peer_share_publish_note",
    "peer_share_resolve",
    "peer_share_fetch",
    "peer_share_fetch_notes",
    // Phase 26 — the voice: a second signing key, confined to public
    // envelopes the way `peer_page_sign` is confined to circle pages.
    "peer_voice_status",
    "peer_voice_next_seq",
    "peer_voice_sign",
    "peer_voice_rotate",
    "peer_voice_sweep",
];

fn main() {
    // Besides the permissions, this emits `cfg(mobile)` / `cfg(desktop)` from
    // the compile target, which is what `local_role()` keys on.
    tauri_plugin::Builder::new(COMMANDS).build();
}
