/// Every command the plugin exposes, by its Rust name. `tauri_plugin::Builder`
/// writes one `allow-*` / `deny-*` permission pair per entry into
/// `permissions/autogenerated/commands/`, and `permissions/default.toml` is
/// where those grants are actually collected. A command missing from this list
/// is unreachable from the webview no matter what the ACL says.
///
/// NO GENERAL RUNNER AMONG THEM, and that is the list's whole design
/// constraint (WI-15.0). There is no `inference_request(url)`, no
/// `inference_exec`, no command taking a path, a host or an argv. The webview
/// renders untrusted book HTML and the daemon's control plane installs and
/// executes backend binaries; every entry below is a named verb over a closed
/// set of arguments, and the routes they reach are literals in `commands.rs`.
const COMMANDS: &[&str] = &[
    // WI-15.0 / WI-15.2 — the runtime's lifecycle
    "inference_status",
    "inference_start",
    "inference_stop",
    // WI-15.1 / WI-15.2 — the manifest and the artifacts
    "inference_models",
    "inference_install_model",
    "inference_remove_model",
    "inference_resource_usage",
    "inference_reveal_models_dir",
    // WI-15.4 / WI-15.5 — the thread
    "inference_generate",
    // WI-15.13 — the gloss. Its own command, not a mode of `generate`,
    // because "no selection can reach an agent" is a property of the call
    // graph and not of a parameter.
    "inference_gloss",
    // WI-15.9 — Kokoro
    "inference_speak",
    // WI-15.10 — the probe
    "inference_probe",
    // WI-15.8 — cloud endpoints. `inference_set_endpoint_key` is WRITE-ONLY;
    // there is deliberately no command that reads a key back.
    "inference_endpoints",
    "inference_add_endpoint",
    "inference_remove_endpoint",
    "inference_set_endpoint_key",
    // WI-15.6 / WI-15.7 — the agents
    "agent_ask",
    "agent_sign_in",
    // Cancellation is one command for every streaming request above, keyed by
    // the request id the caller minted.
    "inference_cancel",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
