import { readFileSync } from 'node:fs'
import path from 'node:path'

/**
 * The third-party notices document, rendered from what is INSTALLED.
 *
 * Four typefaces are bundled into every build. All four are SIL Open Font
 * License 1.1, and OFL §2 makes redistribution conditional on the copyright
 * notice and the licence travelling with the copies — so a build that ships
 * the fonts and not this file does not meet the terms it relies on.
 *
 * Generated rather than written, and generated from `node_modules` rather than
 * from a list in this file, because a hand-kept notices file is the most
 * reliably stale document a project has: nothing fails when a font is added,
 * removed or upgraded, and the notice then describes a build that no longer
 * exists. The gate is `check-third-party-notices.test.mjs`.
 */

export const GENERATED_BY = '<!-- Generated by `pnpm docs:notices`. Do not edit by hand. -->'

/**
 * The packages whose licences must travel with a build.
 *
 * The FONT packages, named here rather than discovered, because "what is
 * bundled into the app" is a decision and not a fact about the dependency
 * tree: a dev dependency's licence has no place in a notices file, and a
 * runtime dependency that ships no asset does not need one either. The
 * matching import lines live in `src/main.tsx`, and the check below asserts
 * that this list and those imports agree.
 */
export const BUNDLED_PACKAGES = [
  '@fontsource-variable/literata',
  '@fontsource-variable/instrument-sans',
  '@fontsource-variable/crimson-pro',
  '@fontsource/ibm-plex-mono',
]

/**
 * The copyright block at the head of a LICENSE, VERBATIM.
 *
 * Reproduced exactly as the package states it rather than reformatted into
 * bullets. The first attempt split on the word `Copyright`, which turned
 * `… (url) Literata-Italic[opsz,wght].ttf: Copyright …` into two entries — one
 * of them ending in a dangling filename and the other a duplicate. A notice
 * whose job is to satisfy "the copyright notice must travel with the copy" is
 * the one document where tidying the text is a defect.
 */
export function copyrightFrom(license) {
  return (license.split(/\n\s*\n/)[0] ?? '').trim()
}

/** The licence body — everything after the copyright block. */
export function licenseBodyFrom(license) {
  const parts = license.split(/\n\s*\n/)
  return parts.slice(1).join('\n\n').trim()
}

/** One installed package's name, version, licence id and LICENSE text. */
export function readPackage(root, name) {
  const at = path.join(root, 'node_modules', name)
  const manifest = JSON.parse(readFileSync(path.join(at, 'package.json'), 'utf8'))
  return {
    name,
    version: manifest.version,
    license: manifest.license,
    text: readFileSync(path.join(at, 'LICENSE'), 'utf8'),
  }
}

/**
 * The whole document.
 *
 * The licence TEXT is emitted once, not four times: all four packages carry
 * the same OFL 1.1 body, and repeating it would make a 700-line file out of a
 * 200-line one while hiding the part that actually differs — the attributions.
 * If a package ever arrives under a different licence, its body is emitted
 * under its own heading, so the shared-text shortcut cannot silently drop a
 * term.
 */
export function renderNotices(packages) {
  const lines = [
    GENERATED_BY,
    '',
    '# Third-party notices',
    '',
    'Paper bundles the typefaces below. They are redistributed under their own',
    'licences, whose terms require this notice to travel with every copy.',
    '',
    '| Package | Version | Licence |',
    '| --- | --- | --- |',
  ]
  for (const one of packages) lines.push(`| \`${one.name}\` | ${one.version} | ${one.license} |`)
  lines.push('')
  lines.push('## Attributions')
  lines.push('')
  for (const one of packages) {
    lines.push(`### \`${one.name}\``)
    lines.push('')
    lines.push('```')
    lines.push(copyrightFrom(one.text))
    lines.push('```')
    lines.push('')
  }

  const bodies = new Map()
  for (const one of packages) {
    const body = licenseBodyFrom(one.text)
    const held = bodies.get(body)
    if (held) held.push(one)
    else bodies.set(body, [one])
  }
  lines.push('## Licence text')
  lines.push('')
  for (const [body, sharing] of bodies) {
    lines.push(`### ${[...new Set(sharing.map((one) => one.license))].join(', ')}`)
    lines.push('')
    lines.push(`Applies to: ${sharing.map((one) => `\`${one.name}\``).join(', ')}.`)
    lines.push('')
    lines.push('```')
    lines.push(body)
    lines.push('```')
    lines.push('')
  }
  return `${lines.join('\n').trimEnd()}\n`
}
