import { existsSync, readFileSync, realpathSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { SHIPPED_TARGETS, readRustCrates, rustLicenseText } from './rustNotices.mjs'

/**
 * The third-party notices document, rendered from what is INSTALLED.
 *
 * Four typefaces are bundled into every build. All four are SIL Open Font
 * License 1.1, and OFL §2 makes redistribution conditional on the copyright
 * notice and the licence travelling with the copies — so a build that ships
 * the fonts and not this file does not meet the terms it relies on.
 *
 * AND THE FONTS WERE NEVER THE WHOLE OBLIGATION. This file enumerated them
 * and nothing else for as long as it existed, while every build also shipped
 * React, pdf.js, foliate-js, Lucide and the Tauri JavaScript API — MIT, ISC
 * and Apache-2.0, every one of which conditions redistribution on the licence
 * and the copyright notice travelling with the copy, in the same words the
 * OFL uses. The bundle carried their code and named none of them. A notice
 * that lists the fonts alone is not a smaller version of the right document;
 * it is a document that is wrong about what the build contains.
 *
 * Generated rather than written, and generated from `node_modules` rather than
 * from a list in this file, because a hand-kept notices file is the most
 * reliably stale document a project has: nothing fails when a font is added,
 * removed or upgraded, and the notice then describes a build that no longer
 * exists. The gate is `check-third-party-notices.test.mjs`, which since this
 * finding also holds the two lists below against `package.json`'s
 * `dependencies` — so a new runtime dependency cannot ship unnamed.
 */

export const GENERATED_BY = '<!-- Generated by `pnpm docs:notices`. Do not edit by hand. -->'

/**
 * The packages whose licences must travel with a build.
 *
 * The FONT packages, named here rather than discovered, because "what is
 * bundled into the app" is a decision and not a fact about the dependency
 * tree: a dev dependency's licence has no place in a notices file, and a
 * runtime dependency that ships no asset does not need one either. The
 * matching import lines live in `src/main.tsx`, and the check below asserts
 * that this list and those imports agree.
 */
export const BUNDLED_PACKAGES = [
  '@fontsource-variable/literata',
  '@fontsource-variable/instrument-sans',
  '@fontsource-variable/crimson-pro',
  '@fontsource/ibm-plex-mono',
]

/**
 * The JavaScript the build ships — the other half of the obligation.
 *
 * Every one of these is imported from `src/` and lands in a bundle. `file`
 * names the licence text INSIDE the package, `vendored` names a copy under
 * `licenses/` for a package that publishes none, and `license` records a
 * choice Paper has made where the package offers one.
 *
 * DECLARED, NOT SEARCHED. The obvious alternative is to try `LICENSE`, then
 * `LICENSE.md`, then `LICENCE`, then `COPYING` — and a package that renames
 * its licence file in an upgrade then silently gets whichever candidate still
 * matches, or none, which is how this file came to be missing eight packages
 * in the first place. A declared name fails loudly instead, which is the only
 * useful behaviour for a document whose failure mode is being quietly wrong.
 *
 * The two Tauri plugin packages publish a `LICENSE.spdx` and no licence text
 * at all — SPDX metadata is a declaration ABOUT the terms, not the terms — so
 * their MIT text is vendored from the crate half of the same plugin at the
 * same version (`tauri-plugin-dialog` 2.7.2, `tauri-plugin-fs` 2.5.1, both
 * from `tauri-apps/plugins-workspace`), and the test compares the vendored
 * copy against the cargo registry when one is checked out. Versionless names,
 * unlike the crates' own vendored files: these are caret-ranged, so a
 * version in the filename would redden the gate on every patch release of a
 * text that has not changed since 2017.
 */
export const BUNDLED_LIBRARIES = [
  { name: 'react' },
  { name: 'react-dom' },
  { name: 'lucide-react' },
  { name: 'pdfjs-dist' },
  { name: 'foliate-js' },
  /* The circle's page signatures. `checkPage` runs its checks cheapest-first
     and verifies the signature LAST, which only works if the crypto is
     synchronous — `crypto.subtle` is not, and BLAKE3 already goes to Rust over
     an async IPC. Both are zero-dependency and both publish a plain `LICENSE`. */
  { name: '@noble/ed25519' },
  { name: '@noble/hashes' },
  /* `Apache-2.0 OR MIT`, and a notice must say which the copy travels under. */
  { name: '@tauri-apps/api', file: 'LICENSE_MIT', license: 'MIT' },
  { name: '@tauri-apps/plugin-dialog', vendored: 'tauri-apps-plugin-dialog-MIT.txt', license: 'MIT' },
  { name: '@tauri-apps/plugin-fs', vendored: 'tauri-apps-plugin-fs-MIT.txt', license: 'MIT' },
]

/**
 * What a bundled library BRINGS WITH IT — the half a partition against
 * `dependencies` cannot see.
 *
 * `react-dom` is ONE ENTRY in `package.json` and TWO LIBRARIES in the bundle:
 * it requires `scheduler`, whose code is in `dist/` and `dist-web/` alike
 * (`unstable_scheduleCallback` is in both, measured) and whose MIT terms
 * condition redistribution on the same notice React's do. The check beside
 * `BUNDLED_LIBRARIES` compares the tables against `package.json`'s DIRECT
 * dependencies, so it was green for as long as `scheduler` shipped unnamed —
 * a partition can only account for the set it partitions.
 *
 * The walk in `check-third-party-notices.test.mjs` closes that: it follows
 * every listed package's own `dependencies` and demands each name it reaches
 * be listed here or excused in `NOT_BUNDLED`.
 *
 * `via` NAMES THE PACKAGE THAT PULLS IT IN, and is not decoration. Under
 * pnpm's default (isolated) linker a transitive package has no
 * `node_modules/<name>` at all — `scheduler` lives under `.pnpm/` and is
 * reachable only from `react-dom` — so `readPackage` has nowhere to look
 * without it.
 */
export const BUNDLED_TRANSITIVE = [{ name: 'scheduler', via: 'react-dom' }]

/**
 * A runtime dependency that ships NOTHING, and why.
 *
 * Empty, and kept because the check is a partition: every key of
 * `dependencies` is either named in a table above or excused here in writing.
 * Without somewhere to say "this one genuinely reaches no build", the next
 * person to add such a dependency has only one way past the gate — widening
 * it — and a widened gate stops being one.
 */
export const NOT_BUNDLED = {}

/**
 * The copyright block at the head of a LICENSE, VERBATIM.
 *
 * Reproduced exactly as the package states it rather than reformatted into
 * bullets. The first attempt split on the word `Copyright`, which turned
 * `… (url) Literata-Italic[opsz,wght].ttf: Copyright …` into two entries — one
 * of them ending in a dangling filename and the other a duplicate. A notice
 * whose job is to satisfy "the copyright notice must travel with the copy" is
 * the one document where tidying the text is a defect.
 */
export function copyrightFrom(license) {
  /* No `?? ''` after the index: `split` on a string always yields at least
   * one element, and a fallback for a case that cannot happen is a branch
   * no test can reach. */
  return license.split(/\n\s*\n/)[0].trim()
}

/** The licence body — everything after the copyright block. */
export function licenseBodyFrom(license) {
  const parts = license.split(/\n\s*\n/)
  return parts.slice(1).join('\n\n').trim()
}

/**
 * The desktop's PLATFORM plugins — the table beside the fonts.
 *
 * Not what the fonts table is. The licence obligation on these two is
 * discharged with every other crate's, under `Rust crates` — they are two rows
 * of the five hundred and ninety-two `rust-crates.json` holds, and this table
 * would be redundant if that were all it said. It is a RECORD OF A DEPENDENCY
 * DECISION (phase 20, D5): two official Tauri plugins taken for a single
 * running instance and a window that remembers itself, each a crate the app
 * crate did not carry before, and each named here with the version the
 * lockfile pins so the decision and the build it describes stay one thing.
 * `lib.rs` must register every one of them, and the notices gate holds that.
 */
export const BUNDLED_PLUGINS = ['tauri-plugin-single-instance', 'tauri-plugin-window-state']

/**
 * A bundled crate's MIT text, VENDORED under `scripts/lib/licenses/` rather
 * than read from `~/.cargo/registry/src/` — that directory exists only after
 * a build has compiled the crate, and the notices test runs before any cargo
 * step on a fresh CI machine. The vendored copy is byte-for-byte from the
 * published crate; a conditional test compares it against the registry when
 * one is present, so an upgrade cannot quietly keep the old text.
 */
export function crateLicenseFor(name, version, root = LICENSES_DIR) {
  const at = path.join(root, `${name}-${version}-MIT.txt`)
  try {
    return readFileSync(at, 'utf8')
  } catch (cause) {
    throw new Error(`${name} ${version}: no vendored licence at ${at} — copy LICENSE_MIT from the published crate`, { cause })
  }
}

/**
 * Every `[[package]]` in a `Cargo.lock`, as name → the versions locked for it.
 *
 * A hand-rolled scan of eight thousand lines of TOML, rather than a parser
 * dependency, because the shape needed is two fields of one table array and
 * `dependency hygiene` costs more than this loop does. A `[[package]]` opens a
 * block; any other line starting `[` closes it.
 *
 * A block with a name and no version THROWS. Dropping it silently would make
 * the crate look absent from the lockfile, and the caller would then report
 * "is it still a dependency?" about a crate that is right there — a true-
 * sounding message pointing at the wrong thing.
 */
export function lockedVersions(lock) {
  const found = new Map()
  let name
  let version
  let inPackage = false
  const flush = () => {
    if (name !== undefined) {
      if (version === undefined) throw new Error(`Cargo.lock has a [[package]] named ${name} with no version — the lockfile is truncated`)
      found.set(name, [...(found.get(name) ?? []), version])
    }
    name = undefined
    version = undefined
  }
  for (const line of lock.split('\n')) {
    const trimmed = line.trim()
    if (trimmed === '[[package]]') {
      flush()
      inPackage = true
      continue
    }
    if (trimmed.startsWith('[')) {
      flush()
      inPackage = false
      continue
    }
    if (!inPackage) continue
    const match = /^(name|version) = "([^"]*)"$/.exec(trimmed)
    if (match === null) continue
    if (match[1] === 'name') name = match[2]
    else version = match[2]
  }
  flush()
  return found
}

/**
 * Those crates as the lockfile pins them, with the licence the manifest
 * records — AND NOT A SINGLE CARGO INVOCATION.
 *
 * ⚠️ THIS USED TO RUN `cargo metadata --offline --locked`, FROM INSIDE A TEST.
 * `--offline` exits 101 when any package in the lockfile is missing from the
 * local registry, and that is the shape of a fresh clone and of a CI runner
 * restoring a `Swatinem/rust-cache` keyed on an older lockfile. This call sat
 * in `test:coverage`, which runs BEFORE `verify.mjs`'s own cargo steps — so
 * any pull request touching `Cargo.lock` could redden CI for a reason having
 * nothing whatever to do with the change, at the step least likely to be
 * suspected. Measured by holding `zbus-4.4.0` out of the registry.
 *
 * `Cargo.lock` is committed, is always present, and answers the version half
 * exactly. The licence half comes from `rust-crates.json`, written where a
 * registry exists by `scripts/refresh-rust-notices.mjs`. Cross-referencing the
 * two is worth more than either alone: a plugin present in the lockfile and
 * absent from the manifest means the manifest is stale, and this says so.
 */
export function readCrates(root, names = BUNDLED_PLUGINS, lock = undefined, declared = undefined) {
  const versions = lockedVersions(lock ?? readFileSync(path.join(root, 'src-tauri', 'Cargo.lock'), 'utf8'))
  const licenses = new Map((declared ?? readRustCrates()).map((one) => [`${one.name}@${one.version}`, one.license]))
  return names.map((name) => {
    /* ALL matches, not the first: Cargo can lock two versions of one crate,
     * and `find()` silently reported whichever the resolver listed first — a
     * notice naming the transitive copy while the lockfile check beside it
     * stayed green. Ambiguity is an error, not a coin toss. */
    const matches = versions.get(name) ?? []
    if (matches.length === 0) throw new Error(`${name} is not in src-tauri/Cargo.lock — is it still a dependency?`)
    if (matches.length > 1) {
      throw new Error(`${name} resolves to ${matches.length} versions (${matches.join(', ')}) — name the one the app ships`)
    }
    const version = matches[0]
    const license = licenses.get(`${name}@${version}`)
    if (license === undefined) {
      throw new Error(`${name} ${version} is in Cargo.lock and not in scripts/lib/rust-crates.json — run \`pnpm docs:rust-notices\``)
    }
    return { name, version, license }
  })
}

/** Where a vendored licence text lives, beside this module. */
export const LICENSES_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), 'licenses')

/**
 * Where a package installed FOR ANOTHER PACKAGE lives.
 *
 * Node's own `node_modules` walk, hand-rolled, starting from the real
 * directory of `via`. Two reasons it is not `require.resolve`:
 * `<name>/package.json` is a subpath, and a package with an `exports` map
 * that does not list it throws `ERR_PACKAGE_PATH_NOT_EXPORTED` — which is
 * every `@tauri-apps/plugin-*` and Paper's own `foliate-js` fork. And the
 * answer must not depend on the linker: under pnpm's default the parent is a
 * symlink into `.pnpm/` with its dependencies BESIDE it, under a hoisted or
 * npm tree the child sits at the root or nested, and the same walk finds all
 * three.
 */
export function packageDirFor(root, name, via = undefined) {
  return via === undefined ? path.join(root, 'node_modules', name) : packageDirThrough(root, via, name)
}

function packageDirThrough(root, via, name) {
  let dir
  try {
    dir = realpathSync(path.join(root, 'node_modules', via))
  } catch (cause) {
    throw new Error(`${name}: its parent ${via} is not installed — the notice cannot describe a package that is not here`, { cause })
  }
  for (;;) {
    const at = path.join(dir, 'node_modules', name)
    if (existsSync(path.join(at, 'package.json'))) return at
    const up = path.dirname(dir)
    if (up === dir) {
      throw new Error(`${name}: not installed anywhere ${via} can see it — is it still a dependency of ${via}?`)
    }
    dir = up
  }
}

/**
 * One installed package's name, version, licence id and licence text.
 *
 * `entry` is a bare name (the fonts, all of which publish a plain `LICENSE`)
 * or a row of `BUNDLED_LIBRARIES`. EVERY failure throws and names the path it
 * looked at: a notice that skips a package it could not read is worse than no
 * notice, because it looks complete.
 */
export function readPackage(root, entry) {
  const { name, file = 'LICENSE', license, vendored, via } = typeof entry === 'string' ? { name: entry } : entry
  const at = packageDirFor(root, name, via)
  let manifest
  try {
    manifest = JSON.parse(readFileSync(path.join(at, 'package.json'), 'utf8'))
  } catch (cause) {
    throw new Error(`${name}: not installed at ${at} — the notice cannot describe a package that is not here`, { cause })
  }
  const from = vendored === undefined ? path.join(at, file) : path.join(LICENSES_DIR, vendored)
  let text
  try {
    text = readFileSync(from, 'utf8')
  } catch (cause) {
    throw new Error(
      `${name}: no licence text at ${from} — name the file it publishes with \`file\`, or vendor one under scripts/lib/licenses/ with \`vendored\``,
      { cause },
    )
  }
  const declared = license ?? manifest.license
  if (typeof declared !== 'string' || declared === '') {
    throw new Error(`${name}: declares no licence — say which terms the build ships it under in BUNDLED_LIBRARIES`)
  }
  return { name, version: versionOf(root, name, manifest), license: declared, text }
}

/**
 * What the build actually resolves for this package.
 *
 * A GIT DEPENDENCY HAS NO VERSION. `foliate-js` is Paper's own fork pinned to
 * a commit, and its manifest says `0.0.0` — which in a notices file reads as a
 * claim about a release rather than as the absence of one. The spec in
 * `package.json` is what the install resolved, so that is what is named, and
 * it carries the SHA that identifies the code being redistributed.
 */
function versionOf(root, name, manifest) {
  const spec = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8')).dependencies?.[name]
  return typeof spec === 'string' && /^(github:|git\+|git:|https?:|file:|link:)/.test(spec) ? spec : manifest.version
}

/**
 * Packages grouped by the exact text they carry, in first-seen order.
 *
 * A Map keyed on the text, so two packages under byte-identical terms share
 * one block and two under terms that differ by so much as a copyright line do
 * NOT — which is the property that matters: three of the packages here are
 * MIT, held by Meta, John Factotum and the Tauri Apps Contributors, and a
 * grouping that keyed on the licence NAME would print one of those three
 * copyright lines and attribute all of it to whoever came first.
 */
function groupByText(packages, textOf = (one) => one.text.trimEnd()) {
  const grouped = new Map()
  for (const one of packages) {
    const text = textOf(one)
    const held = grouped.get(text)
    if (held) held.push(one)
    else grouped.set(text, [one])
  }
  return grouped
}

/**
 * The fence a licence text can be reproduced inside without escaping it.
 *
 * ⚠️ A LICENCE TEXT IS NOT MARKDOWN-INERT, and assuming it was broke this
 * document the first time the Rust crates went into it. `aws-lc-sys` ships a
 * licence whose body contains twenty-six lines beginning with three backticks
 * — it is a markdown file, and it explains itself with code blocks. Inside a
 * three-backtick fence the first of those ENDS the block, and the remainder of
 * that licence, and the two hundred and ninety-six texts after it, render as
 * prose. Nothing errors. The file is the right bytes and the wrong document.
 *
 * CommonMark closes a fence on a run at least as long as the one that opened
 * it, so one backtick longer than the longest leading run is enough, and three
 * is the floor so every text that needs nothing keeps the fence it had. Used
 * for every block here, not only the Rust ones: the fonts and the JavaScript
 * carry the same risk and would have hit it on the first licence that arrived
 * as markdown.
 */
export function fenceFor(text) {
  const runs = [...text.matchAll(/^ {0,3}(`+)/gm)].map((match) => match[1].length)
  return '`'.repeat(Math.max(3, ...runs.map((run) => run + 1)))
}

/**
 * A value put in a markdown table cell verbatim.
 *
 * A code span, because a crate's declared author is `Mads Marquart
 * <mads@marquart.dk>` — angle brackets a markdown renderer reads as a tag, and
 * an autolink where the contents look like an address. Inside a code span they
 * are the characters they are, which is the whole requirement for a copyright
 * holder's name.
 *
 * The fence is one backtick longer than the longest run in the value, which is
 * CommonMark's own rule for embedding backticks, and the pipe is escaped
 * because a pipe ends a cell no matter what encloses it. Neither has occurred
 * in a crate's authors yet; a document that reproduces names must not be one
 * character of somebody's name away from breaking.
 */
export function cell(value) {
  const longest = Math.max(0, ...[...value.matchAll(/`+/g)].map((run) => run[0].length))
  const fence = '`'.repeat(longest + 1)
  const padding = value.startsWith('`') || value.endsWith('`') ? ' ' : ''
  return `${fence}${padding}${value.replaceAll('|', '\\|')}${padding}${fence}`
}

/**
 * The Rust half — several hundred crates, and the licences that make linking
 * them into a redistributed binary conditional on this document existing.
 *
 * THE TABLE FIRST, THE TEXTS AFTER, and that order is the readability
 * decision: the crate list is what a reader scans and the texts are what they
 * consult, so a megabyte of licence body does not sit between the table and
 * anything else. Each distinct text appears ONCE with the crates it covers
 * named above it — 946 licence files across the union collapse to 321 texts,
 * and reproducing them per crate would make a forty-megabyte file out of a
 * one-megabyte one while hiding the part that differs.
 *
 * `crates` is `scripts/lib/rust-crates.json`; `textFor` reads one committed
 * licence text. Both are parameters so the render can be exercised without the
 * committed corpus, and so the corpus can be moved without touching this.
 */
function rustSection(crates, textFor) {
  const lines = [
    '## Rust crates',
    '',
    'The desktop binary statically links the Rust crates below. They are',
    'overwhelmingly MIT and Apache-2.0, and both make permission to redistribute',
    'conditional on the licence and the copyright notice travelling with the copy —',
    'the same condition the typefaces’ OFL imposes, and the reason this section',
    'exists.',
    '',
    'THE BASIS, so it can be checked rather than trusted. This is the NORMAL',
    `dependency closure of the \`app\` binary, taken as the union of the ${SHIPPED_TARGETS.length} targets`,
    `Paper ships (${SHIPPED_TARGETS.join(', ')}).`,
    'Every licence file each crate ships is reproduced, and every NOTICE file with',
    'it — Apache-2.0 §4(d) makes a NOTICE’s attribution text owed separately from',
    'the licence itself. Where a crate offers a choice of terms, every alternative',
    'it offers is reproduced rather than one of them elected on the reader’s behalf.',
    '',
    'Build-dependencies and dev-dependencies are excluded: they compile the build and',
    'the tests, and neither is linked into a shipped binary. Paper’s own crates are',
    'excluded because they are this repository’s, covered by its LICENSE. A crate',
    'only one of those targets links is listed anyway — naming a crate a particular',
    'copy does not contain costs a reader a line, and omitting one it does contain is',
    'the thing the licence forbids.',
    '',
  ]
  /* First-referenced order, so the numbering below follows the table above
     rather than a hash's arbitrary one. */
  const covering = new Map()
  for (const one of crates) {
    for (const sha of one.texts) {
      const held = covering.get(sha)
      if (held) held.push(one)
      else covering.set(sha, [one])
    }
  }
  const standard = crates.filter((one) => one.standard)
  lines.push(`${crates.length} crates, ${covering.size} distinct licence and notice texts.`)
  lines.push('')
  lines.push('| Crate | Version | Licence |')
  lines.push('| --- | --- | --- |')
  for (const one of crates) lines.push(`| \`${one.name}\` | ${one.version} | ${one.license} |`)
  lines.push('')
  if (standard.length > 0) {
    lines.push('### Crates that declare terms and publish no licence text')
    lines.push('')
    lines.push(`These ${standard.length} crates state an SPDX identifier in their manifest and ship no licence`)
    lines.push('file of any kind. The standard text for each identifier they name is reproduced')
    lines.push('below, taken verbatim from the SPDX licence list, and the copyright holders are')
    lines.push('the crate’s own declared authors — the substitution `cargo-about` makes for')
    lines.push('this case. Where a crate declares no authors either, this notice says so rather')
    lines.push('than inventing one.')
    lines.push('')
    lines.push('| Crate | Version | Licence | Copyright holders |')
    lines.push('| --- | --- | --- | --- |')
    for (const one of standard) {
      const holders = one.authors === undefined ? '*the crate declares none*' : one.authors.map(cell).join(', ')
      lines.push(`| \`${one.name}\` | ${one.version} | ${one.license} | ${holders} |`)
    }
    lines.push('')
  }
  lines.push('### Licence and notice texts')
  lines.push('')
  let n = 0
  for (const [sha, sharing] of covering) {
    n++
    lines.push(`#### Text ${n} of ${covering.size}`)
    lines.push('')
    lines.push(`Applies to ${sharing.length} crate${sharing.length === 1 ? '' : 's'}: ${sharing.map((one) => `\`${one.name}\` ${one.version}`).join(', ')}.`)
    lines.push('')
    const text = textFor(sha).trimEnd()
    const fence = fenceFor(text)
    lines.push(fence)
    lines.push(text)
    lines.push(fence)
    lines.push('')
  }
  return lines
}

/**
 * The whole document.
 *
 * THE FONTS' licence TEXT is emitted once, not four times: all four packages
 * carry the same OFL 1.1 body, and repeating it would make a 700-line file
 * out of a 200-line one while hiding the part that actually differs — the
 * attributions. If a font ever arrives under a different licence, its body is
 * emitted under its own heading, so the shared-text shortcut cannot silently
 * drop a term.
 *
 * THE LIBRARIES are reproduced WHOLE instead, grouped where two packages
 * carry byte-identical text, and this difference is deliberate. Splitting a
 * licence into "the copyright block" and "the body" works for the fonts
 * because an OFL file opens with its copyright line; an MIT file opens with
 * `MIT License` and an Apache-2.0 file has no per-package copyright line at
 * all. A heuristic that guessed where the copyright block starts would be
 * wrong about at least one of the five licences here, and being wrong about
 * where a copyright notice ends is the one defect this document cannot carry.
 */
export function renderNotices(packages, libraries = [], crates = [], rust = undefined) {
  const lines = [
    GENERATED_BY,
    '',
    '# Third-party notices',
    '',
    'Paper redistributes the typefaces and the software below. They are covered by',
    'their own licences, whose terms require this notice to travel with every copy.',
    '',
    '## Typefaces',
    '',
    '| Package | Version | Licence |',
    '| --- | --- | --- |',
  ]
  for (const one of packages) lines.push(`| \`${one.name}\` | ${one.version} | ${one.license} |`)
  lines.push('')
  if (libraries.length > 0) {
    lines.push('## JavaScript libraries')
    lines.push('')
    lines.push('The application code every build ships — the packages Paper depends on and')
    lines.push('the ones those bring with them. Each licence is reproduced whole below,')
    lines.push('under the packages it covers; where a package offers a choice of terms, the')
    lines.push('table names the ones this copy travels under. A dependency that reaches no')
    lines.push('build is not listed — `scripts/lib/notices.mjs` records which, and the')
    lines.push('notices test walks what is installed to hold this list to it.')
    lines.push('')
    lines.push('| Package | Version | Licence |')
    lines.push('| --- | --- | --- |')
    for (const one of libraries) lines.push(`| \`${one.name}\` | ${one.version} | ${one.license} |`)
    lines.push('')
    for (const [text, sharing] of groupByText(libraries)) {
      lines.push(`### ${sharing.map((one) => `\`${one.name}\``).join(', ')}`)
      lines.push('')
      lines.push(`${[...new Set(sharing.map((one) => one.license))].join(', ')}, reproduced whole:`)
      lines.push('')
      const fence = fenceFor(text)
      lines.push(fence)
      lines.push(text)
      lines.push(fence)
      lines.push('')
    }
  }
  if (crates.length > 0) {
    /* The sibling table. Recorded, not owed — see `BUNDLED_PLUGINS`. */
    lines.push('## Desktop platform plugins')
    lines.push('')
    lines.push('The desktop build takes these official Tauri plugins for what the platform')
    lines.push('provides and the app must not hand-roll — a single running instance, and a')
    lines.push('window that remembers itself. Their MIT terms are reproduced under')
    lines.push('Attributions below. They are two of the several hundred crates the desktop')
    lines.push('binary links, called out here because taking them was a dependency decision')
    lines.push('rather than a transitive consequence; the rest are accounted for under Rust')
    lines.push('crates.')
    lines.push('')
    lines.push('| Crate | Version | Licence |')
    lines.push('| --- | --- | --- |')
    for (const one of crates) lines.push(`| \`${one.name}\` | ${one.version} | ${one.license} |`)
    lines.push('')
  }
  lines.push('## Attributions')
  lines.push('')
  for (const one of packages) {
    lines.push(`### \`${one.name}\``)
    lines.push('')
    const copyright = copyrightFrom(one.text)
    const fence = fenceFor(copyright)
    lines.push(fence)
    lines.push(copyright)
    lines.push(fence)
    lines.push('')
  }
  /* Each plugin's MIT text WHOLE, one per crate — the two differ in their
   * copyright line (The Tauri Programme in the Commons Conservancy vs Tauri
   * Apps Contributors), so a shared body would misattribute one of them. A
   * notice whose job is "the copyright notice travels with the copy" carried
   * only SPDX identifiers for these two until the 2026-08-28 audit said so. */
  for (const one of crates) {
    lines.push(`### \`${one.name}\``)
    lines.push('')
    const text = crateLicenseFor(one.name, one.version).trimEnd()
    const fence = fenceFor(text)
    lines.push(fence)
    lines.push(text)
    lines.push(fence)
    lines.push('')
  }

  lines.push('## Licence text')
  lines.push('')
  for (const [body, sharing] of groupByText(packages, (one) => licenseBodyFrom(one.text))) {
    lines.push(`### ${[...new Set(sharing.map((one) => one.license))].join(', ')}`)
    lines.push('')
    lines.push(`Applies to: ${sharing.map((one) => `\`${one.name}\``).join(', ')}.`)
    lines.push('')
    const fence = fenceFor(body)
    lines.push(fence)
    lines.push(body)
    lines.push(fence)
    lines.push('')
  }
  /* LAST, and deliberately. This section is a megabyte against the rest of the
     document's twenty-seven kilobytes; put anywhere earlier it buries every
     part a human reads behind three hundred licence texts. The obligation is
     that the terms be present, not that they be first. */
  const rustCrates = rust?.crates ?? []
  if (rustCrates.length > 0) lines.push(...rustSection(rustCrates, rust?.textFor ?? rustLicenseText))
  return `${lines.join('\n').trimEnd()}\n`
}
