import { spawnSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * The third-party notices document, rendered from what is INSTALLED.
 *
 * Four typefaces are bundled into every build. All four are SIL Open Font
 * License 1.1, and OFL §2 makes redistribution conditional on the copyright
 * notice and the licence travelling with the copies — so a build that ships
 * the fonts and not this file does not meet the terms it relies on.
 *
 * Generated rather than written, and generated from `node_modules` rather than
 * from a list in this file, because a hand-kept notices file is the most
 * reliably stale document a project has: nothing fails when a font is added,
 * removed or upgraded, and the notice then describes a build that no longer
 * exists. The gate is `check-third-party-notices.test.mjs`.
 */

export const GENERATED_BY = '<!-- Generated by `pnpm docs:notices`. Do not edit by hand. -->'

/**
 * The packages whose licences must travel with a build.
 *
 * The FONT packages, named here rather than discovered, because "what is
 * bundled into the app" is a decision and not a fact about the dependency
 * tree: a dev dependency's licence has no place in a notices file, and a
 * runtime dependency that ships no asset does not need one either. The
 * matching import lines live in `src/main.tsx`, and the check below asserts
 * that this list and those imports agree.
 */
export const BUNDLED_PACKAGES = [
  '@fontsource-variable/literata',
  '@fontsource-variable/instrument-sans',
  '@fontsource-variable/crimson-pro',
  '@fontsource/ibm-plex-mono',
]

/**
 * The copyright block at the head of a LICENSE, VERBATIM.
 *
 * Reproduced exactly as the package states it rather than reformatted into
 * bullets. The first attempt split on the word `Copyright`, which turned
 * `… (url) Literata-Italic[opsz,wght].ttf: Copyright …` into two entries — one
 * of them ending in a dangling filename and the other a duplicate. A notice
 * whose job is to satisfy "the copyright notice must travel with the copy" is
 * the one document where tidying the text is a defect.
 */
export function copyrightFrom(license) {
  /* No `?? ''` after the index: `split` on a string always yields at least
   * one element, and a fallback for a case that cannot happen is a branch
   * no test can reach. */
  return license.split(/\n\s*\n/)[0].trim()
}

/** The licence body — everything after the copyright block. */
export function licenseBodyFrom(license) {
  const parts = license.split(/\n\s*\n/)
  return parts.slice(1).join('\n\n').trim()
}

/**
 * The desktop's PLATFORM plugins — the table beside the fonts.
 *
 * Not a licence obligation, which is what the fonts table is: these are
 * MIT/Apache crates, and the Rust tree holds several hundred of those that
 * are not enumerated here. This is a RECORD OF A DEPENDENCY DECISION (phase
 * 20, D5): two official Tauri plugins taken for single-instance launch and a
 * remembered window, each a crate the app crate did not carry before, and
 * each named here with the version the lockfile pins so the decision and the
 * build it describes stay one thing. `lib.rs` must register every one of
 * them, and the notices gate holds that.
 */
export const BUNDLED_PLUGINS = ['tauri-plugin-single-instance', 'tauri-plugin-window-state']

/**
 * Those crates as the resolved workspace has them — name, version and the
 * licence the crate declares — from `cargo metadata`, which is the one tool
 * that knows all three. `--offline --locked`: this runs inside a test, and a
 * lockfile the metadata call quietly rewrote is the corruption
 * `dev-docs/versioning.md` records.
 */
/**
 * A bundled crate's MIT text, VENDORED under `scripts/lib/licenses/` rather
 * than read from `~/.cargo/registry/src/` — that directory exists only after
 * a build has compiled the crate, and the notices test runs before any cargo
 * step on a fresh CI machine. The vendored copy is byte-for-byte from the
 * published crate; a conditional test compares it against the registry when
 * one is present, so an upgrade cannot quietly keep the old text.
 */
export function crateLicenseFor(name, version, root = path.join(path.dirname(fileURLToPath(import.meta.url)), 'licenses')) {
  const at = path.join(root, `${name}-${version}-MIT.txt`)
  try {
    return readFileSync(at, 'utf8')
  } catch (cause) {
    throw new Error(`${name} ${version}: no vendored licence at ${at} — copy LICENSE_MIT from the published crate`, { cause })
  }
}

export function readCrates(root, names = BUNDLED_PLUGINS, spawn = spawnSync) {
  const run = spawn(
    'cargo',
    ['metadata', '--format-version', '1', '--offline', '--locked', '--manifest-path', path.join(root, 'src-tauri', 'Cargo.toml')],
    { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
  )
  /* A spawn that never ran has `status: null` and its story in `run.error` —
   * "cargo metadata failed: null" was the whole message when cargo was not
   * on PATH. The real cause travels. */
  if (run.error) throw new Error(`cargo metadata could not run: ${run.error.message}`, { cause: run.error })
  if (run.status !== 0) throw new Error(`cargo metadata failed (exit ${run.status ?? `signal ${run.signal}`}): ${run.stderr}`)
  const packages = JSON.parse(run.stdout).packages
  return names.map((name) => {
    /* ALL matches, not the first: Cargo can resolve two versions of one
     * crate, and `find()` silently reported whichever the resolver listed
     * first — a notice naming the transitive copy while the lockfile check
     * beside it stayed green. Ambiguity is an error, not a coin toss. */
    const matches = packages.filter((one) => one.name === name)
    if (matches.length === 0) throw new Error(`${name} is not in the resolved workspace — is it still a dependency?`)
    if (matches.length > 1) {
      throw new Error(`${name} resolves to ${matches.length} versions (${matches.map((one) => one.version).join(', ')}) — name the one the app ships`)
    }
    const found = matches[0]
    /* `license` may be absent where `license-file` stands in for it (Cargo
     * supports either); say which file rather than "unknown". */
    const license = found.license ?? (found.license_file ? `see ${found.license_file}` : 'unknown')
    return { name, version: found.version, license }
  })
}

/** One installed package's name, version, licence id and LICENSE text. */
export function readPackage(root, name) {
  const at = path.join(root, 'node_modules', name)
  const manifest = JSON.parse(readFileSync(path.join(at, 'package.json'), 'utf8'))
  return {
    name,
    version: manifest.version,
    license: manifest.license,
    text: readFileSync(path.join(at, 'LICENSE'), 'utf8'),
  }
}

/**
 * The whole document.
 *
 * The licence TEXT is emitted once, not four times: all four packages carry
 * the same OFL 1.1 body, and repeating it would make a 700-line file out of a
 * 200-line one while hiding the part that actually differs — the attributions.
 * If a package ever arrives under a different licence, its body is emitted
 * under its own heading, so the shared-text shortcut cannot silently drop a
 * term.
 */
export function renderNotices(packages, crates = []) {
  const lines = [
    GENERATED_BY,
    '',
    '# Third-party notices',
    '',
    'Paper bundles the typefaces below. They are redistributed under their own',
    'licences, whose terms require this notice to travel with every copy.',
    '',
    '| Package | Version | Licence |',
    '| --- | --- | --- |',
  ]
  for (const one of packages) lines.push(`| \`${one.name}\` | ${one.version} | ${one.license} |`)
  lines.push('')
  if (crates.length > 0) {
    /* The sibling table. Recorded, not owed — see `BUNDLED_PLUGINS`. */
    lines.push('## Desktop platform plugins')
    lines.push('')
    lines.push('The desktop build takes these official Tauri plugins for what the platform')
    lines.push('provides and the app must not hand-roll — a single running instance, and a')
    lines.push('window that remembers itself. Their MIT terms are reproduced under')
    lines.push('Attributions below. This file enumerates the bundled fonts and these two')
    lines.push('plugins only; the wider Rust dependency graph is not enumerated here, and')
    lines.push('its crates carry a range of licences of their own (MIT and Apache-2.0')
    lines.push('mostly, with MPL-2.0, BSD, ISC, Unicode-3.0 and Zlib among them).')
    lines.push('')
    lines.push('| Crate | Version | Licence |')
    lines.push('| --- | --- | --- |')
    for (const one of crates) lines.push(`| \`${one.name}\` | ${one.version} | ${one.license} |`)
    lines.push('')
  }
  lines.push('## Attributions')
  lines.push('')
  for (const one of packages) {
    lines.push(`### \`${one.name}\``)
    lines.push('')
    lines.push('```')
    lines.push(copyrightFrom(one.text))
    lines.push('```')
    lines.push('')
  }
  /* Each plugin's MIT text WHOLE, one per crate — the two differ in their
   * copyright line (The Tauri Programme in the Commons Conservancy vs Tauri
   * Apps Contributors), so a shared body would misattribute one of them. A
   * notice whose job is "the copyright notice travels with the copy" carried
   * only SPDX identifiers for these two until the 2026-08-28 audit said so. */
  for (const one of crates) {
    lines.push(`### \`${one.name}\``)
    lines.push('')
    lines.push('```')
    lines.push(crateLicenseFor(one.name, one.version).trimEnd())
    lines.push('```')
    lines.push('')
  }

  const bodies = new Map()
  for (const one of packages) {
    const body = licenseBodyFrom(one.text)
    const held = bodies.get(body)
    if (held) held.push(one)
    else bodies.set(body, [one])
  }
  lines.push('## Licence text')
  lines.push('')
  for (const [body, sharing] of bodies) {
    lines.push(`### ${[...new Set(sharing.map((one) => one.license))].join(', ')}`)
    lines.push('')
    lines.push(`Applies to: ${sharing.map((one) => `\`${one.name}\``).join(', ')}.`)
    lines.push('')
    lines.push('```')
    lines.push(body)
    lines.push('```')
    lines.push('')
  }
  return `${lines.join('\n').trimEnd()}\n`
}
