/**
 * `docs/service-table.md`, rendered from the descriptors (phase 11, WI-11.8).
 *
 * The reference has to be GENERATED or it is a fourth list. The plan's whole
 * argument is `commands.rs`'s opening lesson — three lists that must agree by
 * hand, and a comment explaining what breaks when they do not — and a
 * documentation table maintained beside the code is the most reliably stale
 * of the four, because nothing fails when it drifts.
 *
 * So: this renders, `write-service-docs.mjs` writes, and
 * `check-service-docs.test.mjs` refuses a committed copy that differs. Same
 * three parts, and the same reasoning, as `check-compositions` and the
 * manifest.
 *
 * PURE, and taking the table as an argument rather than importing it: the
 * renderer is then testable against a two-row table, and the one place that
 * reads the real one is the writer.
 */

/** The generated file's first line, so a reader who opens it knows. */
export const GENERATED_BY = '<!-- Generated by scripts/write-service-docs.mjs. Do not edit; edit src/kernel/core/serviceTable.ts. -->'

/** A cell that will not break a markdown table: pipes escaped, no newlines. */
const cell = (text) => String(text).replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ')

/** How a service is spelled on a command line — the same derivation the CLI
 *  does, so the reference and `paper --help` cannot disagree. */
function usage(descriptor) {
  const positional = descriptor.input
    .filter((field) => field.positional !== undefined)
    .slice()
    .sort((a, b) => a.positional - b.positional)
    .map((field) => (field.required === true ? `<${field.name}>` : `[${field.name}]`))
  const flags = descriptor.input
    .filter((field) => field.positional === undefined)
    .map((field) => {
      const spelling = field.type === 'boolean' ? `--${field.name}` : `--${field.name} <${field.type}>`
      return field.required === true ? spelling : `[${spelling}]`
    })
  return [`paper ${descriptor.noun} ${descriptor.verb}`, ...positional, ...flags].join(' ')
}

/**
 * One field, as a bullet under its service.
 *
 * A CLOSED VOCABULARY IS PRINTED. `choices` used to live only in a handler, so
 * this said `--colour — string` while the service accepted three words, and a
 * caller learned them by being refused.
 */
const field = (one) =>
  `  - \`${one.positional === undefined ? `--${one.name}` : `<${one.name}>`}\` — ${one.type}` +
  `${one.required === true ? ', required' : ''}` +
  `${one.choices === undefined ? '' : ` (${one.choices.join(' | ')})`}. ${cell(one.doc)}`

/**
 * The whole reference.
 *
 * Grouped by noun in table order, because that is how the CLI is discovered:
 * nine nouns against six verbs does not read as a flat list of twenty-eight.
 */
/** The answer's shape as a reader sees it: the row, pluralised when many. */
export const shapeOf = (output) => `${output.of}${output.many === true ? '[]' : ''}`

export function renderServiceTable({ table, nouns, grants }) {
  const lines = [
    GENERATED_BY,
    '',
    '# The service table',
    '',
    'Every operation this shelf publishes: its name, the grant the router checks',
    'before the handler sees a byte, the shape it answers in, and how the `paper`',
    'CLI spells it. One declaration produces all four — the router registration,',
    'the client stubs, the command line and this file — so nothing here can drift',
    'from the code without `scripts/check-service-docs` saying so.',
    '',
    '`kind` is the response shape: `req` answers once, `stream` answers in pages',
    'as `stream` frames then `end`. A `stream` exists where one answer would not',
    'fit — a 1,959-row library is not one frame.',
    '',
    '## Grants',
    '',
    'The API surface and the permission surface are one table. A grant is covered',
    'by its exact spelling or by `<family>:*`; a bare `*` covers nothing, because',
    'a wildcard names a family rather than a word.',
    '',
    `${grants.map((grant) => `\`${grant}\``).join(' · ')}`,
    '',
  ]

  for (const noun of nouns) {
    const services = table.filter((one) => one.noun === noun)
    if (services.length === 0) continue
    lines.push(`## \`${noun}\``, '')
    lines.push('| Service | Grant | Kind | Answers | What it does |')
    lines.push('|---|---|---|---|---|')
    for (const one of services) {
      lines.push(
        `| \`${one.name}\` | \`${one.grant}\` | ${one.kind} | \`${cell(shapeOf(one.output))}\` | ${cell(one.summary)} |`,
      )
    }
    lines.push('')
    for (const one of services) {
      lines.push(`### \`${one.name}\``, '', '```', usage(one), '```', '')
      if (one.irreversible === true) {
        lines.push('**Irreversible.** It takes the count it expects to destroy and refuses any other.', '')
      }
      if (one.input.length > 0) {
        lines.push('Arguments:', '')
        for (const each of one.input) lines.push(field(each))
        lines.push('')
      }
      /* THE CROSS-FIELD RULE, said out loud. Without it the usage line above
       * presents `paper mark set <mark>` as a complete call; it is refused. */
      if (one.atLeastOne !== undefined) {
        lines.push(`At least one of \`${one.atLeastOne.join('`, `')}\` is required.`, '')
      }
      if (one.output.columns !== undefined) {
        lines.push(
          `Shown as a table: ${one.output.columns.map((column) => `\`${column}\``).join(', ')}. ` +
            '`--json` carries the whole row.',
          '',
        )
      }
    }
  }
  return `${lines.join('\n').trimEnd()}\n`
}
