#!/usr/bin/env bash
#
# Set the version, in every place that carries one.
#
# THREE FILES AND A LOCKFILE, and the reason this is a script rather than an
# instruction is that a partial application is silent. `package.json` is what
# the repo says; `src-tauri/tauri.conf.json` is what the BUILT APP says, and it
# is the one a reader ever sees — a bundle whose Info.plist disagrees with the
# tag it was cut from is not a thing anyone notices until they are trying to
# work out which build a bug report came from. `src-tauri/Cargo.toml` is what
# the crate says, and `Cargo.lock` records it a second time.
#
# THE LOCKFILE IS THE TRAP. It contains one `version = "0.1.0"` for the app and
# four more for unrelated crates that happen to share the number, so anything
# that rewrites it by pattern corrupts the build in a way `cargo check` will
# then quietly repair on the next run — leaving a dirty tree nobody expected.
# It is regenerated by cargo instead, which is the only thing entitled to.
#
# Usage:  scripts/bump-version.sh <major|minor|patch|X.Y.Z>
#
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"

PKG="package.json"
TAURI="src-tauri/tauri.conf.json"
CARGO="src-tauri/Cargo.toml"
CRATE="app"

die() { printf '%s\n' "$*" >&2; exit 1; }

[ $# -eq 1 ] || die "usage: scripts/bump-version.sh <major|minor|patch|X.Y.Z>"

# --- What each file thinks the version is -----------------------------------
#
# Read separately and compared, because "they were already out of step" is a
# state this repo can reach — three files, one number, nothing enforcing it —
# and bumping from a disagreement picks one at random and hides the other two.

read_pkg()   { python3 -c "import json;print(json.load(open('$PKG'))['version'])"; }
read_tauri() { python3 -c "import json;print(json.load(open('$TAURI'))['version'])"; }
read_cargo() { awk '/^\[package\]/{p=1;next} /^\[/{p=0} p&&/^version *=/{gsub(/[" ]/,"");sub(/^version=/,"");print;exit}' "$CARGO"; }

now_pkg="$(read_pkg)"; now_tauri="$(read_tauri)"; now_cargo="$(read_cargo)"
if [ "$now_pkg" != "$now_tauri" ] || [ "$now_pkg" != "$now_cargo" ]; then
  die "the three files disagree already, so there is no version to bump FROM:
  $PKG    $now_pkg
  $TAURI  $now_tauri
  $CARGO  $now_cargo
Set them to the same value by hand, then run this again."
fi
current="$now_pkg"

# --- What it should become ---------------------------------------------------

case "$1" in
  major|minor|patch)
    IFS=. read -r maj min pat <<<"$current"
    case "$1" in
      major) next="$((maj + 1)).0.0" ;;
      minor) next="${maj}.$((min + 1)).0" ;;
      patch) next="${maj}.${min}.$((pat + 1))" ;;
    esac
    ;;
  [0-9]*.[0-9]*.[0-9]*)
    next="$1"
    ;;
  *)
    die "not a bump or a version: $1"
    ;;
esac

printf 'version %s → %s\n' "$current" "$next"
[ "$current" != "$next" ] || die "already at $next"

# --- Write it ----------------------------------------------------------------
#
# JSON through a JSON parser rather than a regex, so key order and formatting
# survive and a `version` nested somewhere else cannot be hit by accident. The
# TOML edit is anchored to the `[package]` table for the same reason.

python3 - "$PKG" "$next" <<'PY'
import json, sys
path, version = sys.argv[1], sys.argv[2]
with open(path) as f:
    text = f.read()
data = json.loads(text)
data['version'] = version
# Two spaces and a trailing newline, which is what these files already use;
# rewriting the whole document to a different style would bury the one changed
# line in a diff nobody can read.
with open(path, 'w') as f:
    f.write(json.dumps(data, indent=2, ensure_ascii=False) + '\n')
PY

python3 - "$TAURI" "$next" <<'PY'
import json, sys
path, version = sys.argv[1], sys.argv[2]
with open(path) as f:
    data = json.load(f)
data['version'] = version
with open(path, 'w') as f:
    f.write(json.dumps(data, indent=2, ensure_ascii=False) + '\n')
PY

python3 - "$CARGO" "$next" <<'PY'
import re, sys
path, version = sys.argv[1], sys.argv[2]
text = open(path).read()
# The FIRST `version =` inside `[package]` only. A dependency's version is also
# a `version =` at the start of a line in some layouts, and this file has one
# table before any of them.
head, sep, tail = text.partition('[package]')
tail = re.sub(r'(?m)^version\s*=\s*"[^"]*"', f'version = "{version}"', tail, count=1)
open(path, 'w').write(head + sep + tail)
PY

# --- And the lockfile, by the only thing entitled to write it ----------------

if command -v cargo >/dev/null 2>&1; then
  cargo update --manifest-path "$CARGO" --package "$CRATE" --offline >/dev/null 2>&1 \
    || cargo check --manifest-path "$CARGO" >/dev/null 2>&1 \
    || die "the version was written but Cargo.lock could not be updated.
Run 'cargo check --manifest-path $CARGO' and commit the result with it."
else
  die "cargo is not on PATH, so Cargo.lock cannot be updated.
The three version files have been written; the lockfile has not."
fi

# --- Say it landed, everywhere -----------------------------------------------
#
# Re-read rather than trust the writes. Every one of them is a small program
# operating on a file it did not create, and "it probably worked" is how three
# files drift to begin with.

after_pkg="$(read_pkg)"; after_tauri="$(read_tauri)"; after_cargo="$(read_cargo)"
after_lock="$(awk -v c="$CRATE" '
  /^\[\[package\]\]/{n=""}
  /^name = /{gsub(/[",]/,"");sub(/^name = /,"");n=$0}
  /^version = /{if(n==c){gsub(/[",]/,"");sub(/^version = /,"");print;exit}}
' src-tauri/Cargo.lock)"

fail=0
for pair in "$PKG:$after_pkg" "$TAURI:$after_tauri" "$CARGO:$after_cargo" "Cargo.lock:$after_lock"; do
  file="${pair%%:*}"; got="${pair##*:}"
  if [ "$got" != "$next" ]; then
    printf 'NOT SET: %s is %s\n' "$file" "${got:-<unreadable>}" >&2
    fail=1
  fi
done
[ "$fail" -eq 0 ] || die "the bump did not land everywhere — nothing has been committed, fix and re-run"

printf 'set in %s, %s, %s and Cargo.lock\n' "$PKG" "$TAURI" "$CARGO"
